SELECT nombre FROM producto;
SELECT nombre, precio FROM producto;
SELECT * FROM producto;
SELECT nombre, precio AS EUR, ROUND(precio * 1.18,2) AS USD FROM producto;
SELECT nombre AS 'Nombre Producto', precio AS EUR, ROUND(precio * 1.18,2) AS USD FROM producto;
SELECT UPPER(nombre), precio FROM producto;
SELECT LOWER(nombre), precio FROM producto;
SELECT nombre, UPPER(LEFT(nombre,2)) AS iniciales FROM fabricante;
SELECT nombre, ROUND(precio) FROM producto;
SELECT nombre, TRUNCATE(precio,0) FROM producto;
SELECT f.codigo FROM fabricante f, producto p WHERE f.codigo = p.codigo_fabricante;
SELECT f.codigo FROM fabricante f, producto p WHERE f.codigo = p.codigo_fabricante GROUP BY f.codigo;
SELECT nombre FROM fabricante ORDER BY nombre ASC;
SELECT nombre FROM fabricante ORDER BY nombre DESC;
SELECT nombre, precio FROM producto ORDER BY nombre ASC, precio DESC;
SELECT * FROM fabricante LIMIT 5;
SELECT * FROM fabricante LIMIT 3,2;
SELECT nombre, precio FROM producto ORDER BY precio ASC LIMIT 1;
SELECT nombre, precio FROM producto ORDER BY precio DESC LIMIT 1;
SELECT p.nombre FROM fabricante f JOIN producto p ON p.codigo_fabricante = 2 GROUP BY p.nombre;
SELECT p.nombre, p.precio, f.nombre FROM producto p JOIN fabricante f ON p.codigo_fabricante = f.codigo;
SELECT p.nombre, p.precio, f.nombre FROM producto p JOIN fabricante f ON p.codigo_fabricante = f.codigo ORDER BY f.nombre ASC;
SELECT p.codigo, p.nombre, f.codigo AS codigo_fabricante, f.nombre AS nombre_fabricante FROM producto p JOIN fabricante f ON p.codigo_fabricante = f.codigo;
SELECT p.nombre, MIN(p.precio), f.nombre FROM producto p JOIN fabricante f ON p.codigo_fabricante = f.codigo;
SELECT p.nombre, MAX(p.precio), f.nombre FROM producto p JOIN fabricante f ON p.codigo_fabricante = f.codigo;
SELECT * FROM producto p JOIN fabricante f ON p.codigo_fabricante = f.codigo WHERE f.nombre = 'Lenovo';
SELECT * FROM producto p JOIN fabricante f ON p.codigo_fabricante = f.codigo WHERE f.nombre = 'Crucial' AND p.precio > 200;
SELECT * FROM producto p JOIN fabricante f ON p.codigo_fabricante = f.codigo WHERE f.nombre = 'Asus' OR f.nombre = 'Hewlett-Packard' OR f.nombre = 'Seagate';
SELECT * FROM producto p JOIN fabricante f ON p.codigo_fabricante = f.codigo WHERE f.nombre IN ('Asus','Hewlett-Packard','Seagate');
SELECT * FROM producto p JOIN fabricante f ON p.codigo_fabricante = f.codigo WHERE f.nombre LIKE '%e';
SELECT p.nombre, p.precio, f.nombre FROM producto p JOIN fabricante f ON p.codigo_fabricante = f.codigo WHERE f.nombre LIKE '%w%';
SELECT p.nombre, p.precio, f.nombre FROM producto p JOIN fabricante f ON p.codigo_fabricante = f.codigo WHERE p.precio >= 180 ORDER BY p.precio DESC, p.nombre ASC;
SELECT f.codigo, f.nombre FROM fabricante f JOIN producto p ON f.codigo = p.codigo_fabricante GROUP BY f.nombre;
SELECT f.codigo, f.nombre, p.nombre AS producto FROM fabricante f LEFT JOIN producto p ON f.codigo = p.codigo_fabricante GROUP BY f.codigo;
SELECT f.codigo, f.nombre, p.nombre AS producto FROM fabricante f LEFT JOIN producto p ON f.codigo = p.codigo_fabricante WHERE p.codigo IS NULL;
SELECT p.nombre, f.nombre AS fabricante  FROM producto p, fabricante f WHERE p.codigo_fabricante = f.codigo AND f.nombre = 'Lenovo';
SELECT * FROM producto p WHERE p.precio = (SELECT MAX(p.precio) FROM producto p, fabricante f WHERE p.codigo_fabricante = f.codigo AND f.nombre = 'Lenovo');
SELECT p.nombre FROM producto p JOIN fabricante f ON p.codigo_fabricante = f.codigo WHERE p.precio = (SELECT MAX(p.precio) FROM producto p, fabricante f WHERE p.codigo_fabricante = f.codigo AND f.nombre = 'Lenovo') AND f.nombre = 'Lenovo';
SELECT p.nombre FROM producto p JOIN fabricante f ON p.codigo_fabricante = f.codigo WHERE p.precio = (SELECT MIN(p.precio) FROM producto p, fabricante f WHERE p.codigo_fabricante = f.codigo AND f.nombre = 'Hewlett-Packard') AND f.nombre = 'Hewlett-Packard';
SELECT * FROM producto p WHERE p.precio >= (SELECT MAX(p.precio) FROM producto p, fabricante f WHERE p.codigo_fabricante = f.codigo AND f.nombre = 'Lenovo');
SELECT * FROM producto p JOIN fabricante f ON p.codigo_fabricante = f.codigo WHERE f.nombre = 'Asus' AND p.precio > (SELECT AVG(p.precio) FROM producto p JOIN fabricante f ON p.codigo_fabricante = f.codigo WHERE f.nombre = 'Asus');
/* CONSULTAS BBDD UNIVERSIDAD */
SELECT p.apellido1, p.apellido2, p.nombre FROM persona p WHERE p.tipo = 'alumno' ORDER BY p.apellido1 ASC, p.apellido2 ASC, p.nombre ASC;
SELECT p.nombre, p.apellido1, p.apellido2 FROM persona p WHERE p.tipo = 'alumno' AND telefono IS NULL;
SELECT * FROM persona p WHERE p.tipo = 'alumno' AND YEAR(fecha_nacimiento) = '1999';
SELECT * FROM persona p WHERE p.tipo = 'profesor' AND nif LIKE '%K' AND telefono IS NULL;
SELECT * FROM  asignatura WHERE cuatrimestre = 1 AND curso = 3 AND id_grado = 7;
SELECT p.apellido1, p.apellido2, p.nombre, d.nombre AS departamento FROM persona p JOIN profesor pr ON p.id = pr.id_profesor JOIN departamento d ON pr.id_departamento = d.id ORDER BY p.apellido1 ASC, p.apellido2 ASC, p.nombre ASC;
SELECT p.nif, p.nombre, p.apellido1, p.apellido2, a.nombre AS asignatura, c.anyo_inicio, c.anyo_fin FROM persona p JOIN alumno_se_matricula_asignatura m ON p.id = m.id_alumno JOIN asignatura a ON m.id_asignatura = a.id JOIN curso_escolar c ON m.id_curso_escolar = c.id WHERE p.nif = '26902806M';
SELECT d.nombre FROM departamento d JOIN profesor pr ON d.id = pr.id_departamento JOIN persona p ON pr.id_profesor = p.id JOIN asignatura a ON p.id = a.id_profesor JOIN grado g ON g.id = a.id_grado WHERE g.nombre LIKE '%Informática%2015%' GROUP BY d.id;
SELECT p.nombre, p.apellido1, p.apellido2 FROM persona p JOIN alumno_se_matricula_asignatura m ON m.id_alumno = p.id JOIN asignatura a ON a.id = m.id_asignatura JOIN curso_escolar c ON c.id = m.id_curso_escolar WHERE c.anyo_inicio = '2018' GROUP BY p.id;
/* CLAUSULAS LEFT Y RIGHT JOIN */
SELECT d.nombre, p.apellido1, p.apellido2, p.nombre FROM persona p LEFT JOIN profesor pr ON pr.id_profesor = p.id LEFT JOIN departamento d ON d.id = pr.id_departamento WHERE p.tipo = 'profesor' ORDER BY d.nombre ASC, p.apellido1 ASC, p.apellido2 ASC, p.nombre ASC;
SELECT p.nombre, p.apellido1, p.apellido2 FROM persona p LEFT JOIN profesor pr ON pr.id_profesor = p.id LEFT JOIN departamento d ON d.id = pr.id_departamento WHERE p.tipo = 'profesor' AND d.nombre IS NULL;
/* SELECCIONA DEPARTAMENTOS SIN PROFESOR ASIGNADO: PRIMERA RIGHT JOIN, SEGUNDA LEFT JOIN */
SELECT d.nombre FROM persona p JOIN profesor pr ON pr.id_profesor = p.id RIGHT JOIN departamento d ON d.id = pr.id_departamento WHERE p.nombre IS NULL;
SELECT d.nombre FROM departamento d LEFT JOIN profesor pr ON pr.id_departamento = d.id LEFT JOIN persona p ON p.id = pr.id_profesor WHERE p.nombre IS NULL;
/**/
SELECT p.nombre, p.apellido1, p.apellido2 FROM persona p LEFT JOIN asignatura a ON a.id_profesor = p.id WHERE p.tipo = 'profesor' AND a.nombre IS NULL GROUP BY p.id;
SELECT a.nombre FROM persona p RIGHT JOIN asignatura a ON a.id_profesor = p.id WHERE p.nombre IS NULL;
SELECT d.nombre FROM alumno_se_matricula_asignatura m JOIN asignatura a ON a.id = m.id_asignatura JOIN profesor pr USING(id_profesor) RIGHT JOIN departamento d ON d.id = pr.id_departamento WHERE a.nombre IS NULL AND a.id_profesor IS NULL;
/* CONSULTAS RESUMEN */
SELECT COUNT(*) FROM persona p WHERE p.tipo = 'alumno'; 
SELECT COUNT(*) FROM persona p WHERE p.tipo = 'alumno' AND YEAR(fecha_nacimiento) = '1999';
SELECT d.nombre, COUNT(p.id) AS profesores FROM departamento d JOIN profesor pr ON pr.id_departamento = d.id JOIN persona p ON p.id = pr.id_profesor GROUP BY d.id ORDER BY profesores ASC;
SELECT d.nombre, COUNT(p.id) AS profesores FROM departamento d LEFT JOIN profesor pr ON pr.id_departamento = d.id LEFT JOIN persona p ON p.id = pr.id_profesor GROUP BY d.id ORDER BY profesores ASC;
SELECT g.nombre, COUNT(a.id) AS asignaturas FROM grado g LEFT JOIN asignatura a ON a.id_grado = g.id GROUP BY g.id ORDER BY asignaturas ASC;
SELECT g.nombre, COUNT(a.id) AS asignaturas FROM grado g LEFT JOIN asignatura a ON a.id_grado = g.id GROUP BY g.id HAVING COUNT(asignaturas) > 40 ORDER BY asignaturas ASC;
SELECT g.nombre, a.tipo, SUM(a.creditos) AS creditos FROM asignatura a JOIN grado g ON g.id = a.id_grado GROUP BY g.id, a.tipo ORDER BY creditos;
SELECT c.anyo_inicio, SUM(m.id_alumno) AS alumnos FROM alumno_se_matricula_asignatura m JOIN curso_escolar c ON c.id = m.id_curso_escolar GROUP BY m.id_alumno;
SELECT p.id, p.nombre, p.apellido1, p.apellido2, SUM(a.id) AS asignaturas FROM persona p JOIN asignatura a ON a.id_profesor = p.id WHERE p.tipo = 'profesor' GROUP BY p.id ORDER BY asignaturas ASC;
SELECT * FROM persona p WHERE p.tipo = 'alumno' AND fecha_nacimiento = (SELECT MAX(fecha_nacimiento) FROM persona);
SELECT p.nombre, p.apellido1, p.apellido2 FROM persona p JOIN profesor pr ON pr.id_profesor = p.id LEFT JOIN asignatura a ON a.id_profesor = p.id WHERE p.tipo = 'profesor' AND a.id_profesor IS NULL;